---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 11.01.2020 22:27
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

function selectVizir()

    usePreviousSnap(true)
    local img1, c1 = findImage(vizirs, RegHalfUp)
    local img2, c2 = findImage(sendVizir, RegHalfBottom)
    local cY = c1:getY() + (c2:getY() - c1:getY()) / 2
    local column = rnd(1, 3)
    local row = rnd(1, 3)

    local vX = 0
    local vY = 0
    if (column == 1) then
        vX = img1:getX() - (c1:getX() - img1:getX())
    elseif (column == 2) then
        vX = c1:getX()
    else
        vX = c1:getX() + 2 * (c1:getX() - img1:getX())
    end

    if (row == 1) then
        vY = c1:getY() + (c2:getY() - c1:getY()) / 3
    elseif (row == 2) then
        vY = cY
    else
        vY = c1:getY() + 2 * (c2:getY() - c1:getY()) / 3
    end
    click(Location(vX, cY))
    usePreviousSnap(false)
    while (existsClick(sendVizir, RegHalfBottom, 0.1)) do
        wait(0.1)
    end

end

function sendToFriends()

    while (not (findImage(selectFriend, RegHalfUp))) do
        existsClick(friends, RegHalfBottom, 0.1)
    end

    i = 0

    while (i <= 11) do
        usePreviousSnap(true)
        if (findImage(selectFriend2, RegHalfUp)) then
            existsClick(selectFriend2, RegHalfUp, 0.1)
        elseif (findImage(selectFriend, RegHalfUp)) then
            existsClick(selectFriend, RegHalfUp, 0.1)
        end
        usePreviousSnap(false)

        j = 0
        while (waitTimeoutExistAndClick(addPractice, RegHalfBottom, 1.1, 0.1) and i <= 11) do

            if (waitTimeout(vizirs, RegHalfUp, 1.1)) then
                selectVizir()
            end
            i = i + 1
            j = j + 1
            if (j % 2 == 0) then
                dragDrop(Point_2, Point_1)
            end
        end
        backTo(xx2)
    end
    wait(0.5)
    while (existsClick(xx2, RegHalfUp, 0.1)) do
        wait(0.1)
    end

    --local img,c = findImage(countPractice, RegQuaterBottom)
    --local xX = img:getX()
    --local yY = img:getY()
    --local xW = img:getW()
    --local yH = img:getH()
    --local r = Region(xX + xW, yY, xW / 2, yH)
    --r:highlight(1)
    --num = numberOCR(r, "v")
    --toast(num)

end

function collectAcademy()
    setImagePath(localPath .. "image")
    while (not (findImage(academyImg, RegScreen))) do
        dragDrop(Point_2, Point_1)
    end
    if (getNotCollectedReg(academyImg, RegScreen)) then
        wait(1)
        setImagePath(localPath .. "image" .. "/academy")
        click(Location(screenX / 2, screenY / 8))
        click(Location(screenX / 2, screenY / 8))
        click(Location(screenX / 2, screenY / 8))
        waitTimeoutExistAndClick(takeAway, RegHalfBottom, 0.7, 0.1)
        if (isFriends) then
            sendToFriends()
        end
        if (existsClick(autoComplete, RegQuaterBottom, 0.1)) then
            click(Location(screenX / 2, screenY / 2))
            wait(0.5)
            existsClick(avtoAddVizirs, RegQuaterBottom, 0.1)
            existsClick(avtoAddVizirs, RegQuaterBottom, 0.1)
        else
            local allVizirs = findAllNoFindException(oneComplete, RegScreen)
            usePreviousSnap(true)
            for i, im in ipairs(allVizirs) do
                click(Location(im:getCenter():getX(), im:getY() - im:getH()))
                wait(0.3)
                for j = 1, 5 do
                    click(Location(screenX / 2, screenY / 4))
                    click(Location(screenX / 2, screenY / 4))
                end
            end

            usePreviousSnap(false)
            click(Location(screenX / 2, screenY / 2))
            while (waitTimeoutExistAndClick(addVizir, RegScreen, 0.7, 0.1)) do
                if (waitTimeout(vizirs, RegHalfUp, 1.1)) then
                    selectVizir()
                end
            end
        end
        setImagePath(localPath .. "image")
        backTo(academyImg)
    end
end

