---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 21.05.2020 1:19
---

lvl1_min = { 150, 2, 80 }
lvl1_max = { 151, 2, 85 }

lvl2_min = { 74, 40, 39 }
lvl2_max = { 75, 42, 41 }

lvl3_min = { 189, 25, 46 }
lvl3_max = { 191, 40, 47 }

lvl4_min = { 342, 38, 63 }
lvl4_max = { 344, 41, 69 }

lvl5_min = { 29, 86, 47 }
lvl5_max = { 30, 95, 50 }

lvl6_min = { 16, 80, 50 }
lvl6_max = { 16, 98, 50 }

lvl7_min = { 40, 59, 69 }
lvl7_max = { 41, 69, 83 }

lvl8_min = { 76, 35, 75 }
lvl8_max = { 80, 55, 86 }

vizirFramesDetected = false
vizirRegion = {}