---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 11.01.2020 23:43
---

localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")
function collectBonuses()
    setImagePath(localPath .. "image")
    while (not (findImage(chertog, RegScreen))) do
        dragDrop(Point_1, Point_2)
    end
    if (getNotCollectedReg(chertog, RegScreen)) then
        wait(1)
        setImagePath(localPath .. "image" .. bonusImagePath)
        x = screenX * 0.84
        y = screenY * 0.948
        x1 = 0
        y1 = 0
        if (existsClick(allServerRate, RegHalfBottom, 1)) then
            wait(0.2)
            click(Location(x, y))
            wait(0.5)
            click(Location(x, y))
            alImg, alCenter = findImage(alliancesBonus, RegQuaterUp)
            x1 = alCenter:getX()
            y1 = alCenter:getY()
            click(Location(x1, y1))
            wait(0.2)
            click(Location(x, y))
            wait(0.2)
            click(Location(x, y))
            click(Location(x1 + x1 / 2, y1))
            wait(0.2)
            click(Location(x, y))
            wait(0.2)
            click(Location(x, y))
        end
        backTo(serverRate)
        if( existsClick(serverRate, RegHalfUp, 1)) then
            wait(0.2)
            click(Location(x, y))
            wait(0.2)
            click(Location(x, y))
            click(Location(x1, y1))
            wait(0.2)
            click(Location(x, y))
            wait(0.2)
            click(Location(x, y))
            click(Location(x1 + x1 / 2, y1))
            wait(0.2)
            click(Location(x, y))
            wait(0.2)
            click(Location(x, y))
        end
    end
    setImagePath(localPath .. "image")
    backTo(chertog)
    if (getNotCollectedReg(chertog, RegScreen)) then
        collectBonuses()
    end
end
