---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 09.02.2020 22:39
---

require(localPath .. "utils")
require(localPath .. "sultanObjects")

localPath = scriptPath()
local chAccPath = "/change"
local mainscr = Pattern("mainscr.png")
local googleAcc = Pattern("google-acc.png")
local account = Pattern("account.png")
local addAccount = Pattern("addAccount.png")
local delimiter = Pattern("delimiter.png")
local exitAcc = Pattern("exit.png")
local changeAcc = Pattern("changeAcc.png")

function waitOneOfCloseBtn(image1, image2, reg, timeout)
    imgCC = false


    while (not (findImageLowSimilar(image1, reg)) and not (findImageLowSimilar(image2, reg)) and timeout > 0) do
        wait(0.5)
        timeout = timeout - 1
    end

    usePreviousSnap(true)
    if (findImage(image1, reg)) then
        imgCC = image_Center
    elseif (findImage(image2, reg)) then
        imgCC = image_Center
    end
    usePreviousSnap(false)

    return imgCC
end

function closeNotifications()
    setImagePath(localPath .. "image")

    while (waitOneOfCloseBtn(xx, xx2, RegRight, 3)) do
        click(imgCC)
    end
    setImagePath(localPath .. "image" .. chAccPath)
end

function chooseAcc(accNum)
    local point1 = Location(screenX / 2, screenY / 2 - screenY / 8)
    local point2 = Location(screenX / 2, screenY / 2 + screenY / 8)
    while (not(findImage(Pattern("acc".. accNum .. ".png"), RegScreen))) do
        dragDrop(point2, point1)
    end
    usePreviousSnap(true)
    existsClick(Pattern("acc".. accNum .. ".png"), RegScreen, 0.2)
    usePreviousSnap(false)
    waitTimeout(mainscr, RegQuaterUp, 3)
    while (findImage(mainscr, RegQuaterUp)) do
        click(pCenter)
        wait(1)
    end
end

function changeAccount(accNum)

    backTo(account)
    setImagePath(localPath .. "image" .. chAccPath)
    existsClick(account, RegQuaterBottom, 0.1)
    waitExistAndClick(changeAcc, RegMiddle, 0.1)
    if (waitTimeout(exitAcc, RegScreen, 1)) then
        waitExistAndClick(exitAcc, RegMiddle, 0.1)
        waitTimeout(mainscr, RegQuaterUp, 3)
        while (findImage(mainscr, RegQuaterUp)) do
            click(pCenter)
            wait(1)
        end
        closeNotifications()
        backTo(account)
        waitExistAndClick(account, RegQuaterBottom, 0.1)
        waitExistAndClick(changeAcc, RegMiddle, 0.1)
    end

    waitExistAndClick(googleAcc, RegScreen, 0.1)
    wait(1)
    chooseAcc(accNum)
    wait(1)
    closeNotifications()
end