---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by enichegovskiy.
--- DateTime: 04.05.2020 13:45
---
require(localPath .. "arenalvl")

function intToRGB(value)
    local b = value % 0x100
    value = math.floor(value / 0x100)
    local g = value % 0x100
    value = math.floor(value / 0x100)
    local r = value % 0x100
    return r, g, b
end

function rgbToHsl(r, g, b)
    r = r / 255
    g = g / 255
    b = b / 255
    local max, min = math.max(r, g, b), math.min(r, g, b)
    local h = (max + min) / 2
    local s = (max + min) / 2
    local l = (max + min) / 2
    if (max == min) then
        h = 0
        s = 0
    else
        d = max - min;
        s = l > .5 and d / (2 - max - min) or d / (max + min)
        if (max == r) then
            h = (g - b) / d + (g < b and 6 or 0)
        elseif (max == g) then
            h = (b - r) / d + 2
        elseif (max == b) then
            h = (r - g) / d + 4
        end
    end

    h = h / 6
    return math.floor(h * 360), math.floor(s * 100), math.floor(max * 100)
end

function islvl(minColor, maxColor, h, l, s)
    if (h >= minColor[1] and h <= maxColor[1]) then
        if ((l >= minColor[2] and l <= maxColor[2]) or (l >= maxColor[2] and l <= minColor[2])) then
            if ((s >= minColor[3] and s <= maxColor[3]) or (s >= maxColor[3] and s <= minColor[3])) then
                return true
            end
        end
    end
    return false
end

function detectLvl(h, l, s)
    if (islvl(lvl1_min, lvl1_max, h, l, s)) then
        return 1
    elseif (islvl(lvl2_min, lvl2_max, h, l, s)) then
        return 2
    elseif (islvl(lvl3_min, lvl3_max, h, l, s)) then
        return 3
    elseif (islvl(lvl4_min, lvl4_max, h, l, s)) then
        return 4
    elseif (islvl(lvl5_min, lvl5_max, h, l, s)) then
        return 5
    elseif (islvl(lvl6_min, lvl6_max, h, l, s)) then
        return 6
    elseif (islvl(lvl7_min, lvl7_max, h, l, s)) then
        return 7
    elseif (islvl(lvl8_min, lvl8_max, h, l, s)) then
        return 8
    end
    return 0
end

function findVizirLvl(region)

    local minX = region:getX()
    local maxX = region:getX() + region:getW() - 1
    local minY = region:getY()
    local maxY = region:getY() + region:getH() - 1

    snapshotColor()
    lvl = 0
    for x = minX, maxX, 10 do
        for y = minY, maxY, 10 do
            local tx = x
            local ty = y
            local tr, tg, tb = getColor(Location(tx, ty))
            local h, l, s = rgbToHsl(tr, tg, tb)

            lvl = detectLvl(h, l, s)
            if (lvl ~= 0) then
                return lvl
            end
        end
    end

    return false
end

function findColors(region)

    local minX = region:getX()
    local maxX = region:getX() + region:getW() - 1
    local minY = region:getY()
    local maxY = region:getY() + region:getH() - 1

    snapshotColor()
    local result = {}
    local j = 0;
    local points = 0;

    str = ""
    for x = minX, maxX,8 do
        for y = minY, maxY,8 do
            point = points + 1
            local tx = x
            local ty = y
            local tr, tg, tb = getColor(Location(tx, ty))
            str = str .. tr .. "," .. tg .. "," .. tb .. "\r\n"
        end
    end
    simplelog(str)
    wait(5)


    return result
end