---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 08.01.2020 23:47
---

function showDlg(flag)
    dialogInit()

    addSeparator()
    addTextView("")
    newRow()
    addCheckBox("isHarem", "Гарем    \t", false)
    addCheckBox("isCollectHeirs", "Дети      \t", false)
    addCheckBox("isGadalka", "Гадалка\t", false)
    newRow()
    addCheckBox("isAcademy", "Академ\t", false)
    addCheckBox("isFriends", "Друзья\t", false)
    addCheckBox("isWalking", "Прогулки\t", false)
    newRow()
    addCheckBox("isMinistery", "Послы  \t", false)
    addCheckBox("isSendToTrip", "Trip \t", false)
    addEditNumber("sendToTrip",  0)
    newRow()

    newRow()
    addSeparator()
    addTextView("")
    newRow()
    addCheckBox("ordersExperience", "Опыт\t", false)
    addCheckBox("isRgmt", "Полк\t", false)
    addCheckBox("isPuzzle", "Пазлы\t", false)
    addCheckBox("stars", "Stars\t", false)
    newRow()
    addSeparator()
    if (flag) then
        addTextView("")
        newRow()
        addCheckBox("getGold", "Сундуки\t      ", false)
        addSeparator()
    end

    addTextView("")
    newRow()
    addCheckBox("isContinueFight", "Арена - Продолжить бой \t", false)
    newRow()
    addTextView("   Бонусы арены")
    addRadioGroup("pointsIdx", 1)
    addRadioButton("0", 0)
    addRadioButton("1", 1)
    addRadioButton("2", 2)
    newRow()
    addSeparator()
    addTextView("")
    addCheckBox("immersiveMode", "Immersive Mode\t", true)


    dialogShow("Sultan Script v " .. version)
    return true
end