---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 11.01.2020 22:27
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

local addVizir = Pattern("addVizir.png")
local applyAdd = Pattern("apply.png")
local fedya = Pattern("fedya.png")
local fedyaHall = Pattern("fedya-hall.png")
local getQuest = Pattern("get-quest.png")
local vpered = Pattern("vpered.png")
local cls = Pattern("xx.png")
local approve = Pattern("approve.png.png")
local nofedya = Pattern("nofedya.png")
local fedyaPath = "/fedya"

function sendFedyaTasks()
    setImagePath(localPath .. "image")
    while (not (findImage(fedya, RegScreen))) do
        dragDrop(Point_2, Point_1)
    end
    usePreviousSnap(true)
    existsClick(fedya, RegScreen, 0.1)
    usePreviousSnap(false)
    setImagePath(localPath .. "image" .. fedyaPath)
    waitTimeoutOneOf(nofedya, fedyaHall, RegScreen, 0.6)
    if (not(findImageLowSimilar(nofedya, RegScreen))) then
        waitExistAndClick(fedyaHall, RegScreen, 0.1)
        dragDrop(Point_1, Point_2)

        waitExistAndClick(getQuest, RegHalfBottom, 0.1)
        if (not(findImage(cls, RegQuaterRight))) then
            if (findImage(addVizir, RegHalfBottom)) then
                existsClick(addVizir, RegHalfBottom, 0.1)
                click(pCenter)
                existsClick(applyAdd, RegHalfBottom, 0.1)
            else
                existsClick(applyAdd, RegHalfBottom, 0.1)
                existsClick(approve, RegHalfBottom, 0.1)
            end
        else
            existsClick(cls, RegQuaterRight, 0.1)
        end

        click(topCenterPoint)
        backTo(fedyaHall)
    end
    setImagePath(localPath .. "image")
    backTo(fedya)
end