---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Sphehr.
--- DateTime: 11.01.2020 22:27
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

function collectGadalka()
    setImagePath(localPath .. "image")
    while (not (findImage(gadalka, RegHalfBottom))) do
        dragDrop(Point_2, Point_1)
    end
    if (getNotCollectedReg(gadalka, RegHalfBottom)) then
        wait(1)
        if (findImage(coffee, RegHalfBottom)) then
            click(image_Center)
            wait(2)
            --usePreviousSnap(true)
            --if (findImage(littleChest, RegQuaterBottom)) then
            --    bonusImg, center = findImage(littleChest, RegQuaterBottom)
            --    x = center:getX()
            --    y = center:getY() - 10
            --    click(Location(x, y))
            --    wait(0.2)
            --
            --end
            --usePreviousSnap(false)
        end

        if(findImage(chestPoint,RegHalfBottom))then
            usePreviousSnap(true)
            giftBonuses = findAll(chestPoint)
            for i, m in ipairs(giftBonuses) do
                t = m:getTarget()
                x = t:getX()
                y = t:getY() * 0.948
                r = Region(x,y, 5, 5)
                r:highlight()
                click(Location(x, y))
                existsClick(xx2, RegScreen, 0.1)
            end
            usePreviousSnap(false)
        end

        wait(2)
        backTo(gadalka)
    end
end