---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 21.05.2020 23:13
---
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

function collectGunAndWheel()

    waitOneOf3ExistAndClick(puzzleIcon, puzzleIcon2, puzzleIcon3, RegRightLine, 0.1)
    setImagePath(localPath .. "image" .. puzzlePath)

    waitExistAndClick(gun, RegHalfUp, 0.1)
    waitOneOfExistAndClick(shootDescr, shootDescr2, RegMiddle, 0.1)
    usePreviousSnap(true)
    existsClick(shoot, RegQuaterBottom, 0.1)
    wait(1.5)
    click(Location(screenX / 2, screenY / 2))
    clickBack()
    usePreviousSnap(false)
    while (not (findImage(wheel, RegHalfBottom))) do
        dragDrop(Point_4, Point_1)
    end
    existsClick(wheel, RegHalfBottom, 0.1)
    while (not (findImage(wheelBtn, RegHalfBottom))) do
        click(Location(screenX / 2, screenY / 2))
        wait(0.1)
    end
    usePreviousSnap(true)
    local img, cntr = findImage(wheelBtn, RegHalfBottom)
    usePreviousSnap(false)

    while (not(findImage(wheelFinished, RegHalfBottom))) do
        click(cntr)
    end

    setImagePath(localPath .. "image")
    backTo(shop)

end