---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 16.01.2020 0:42
---

localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

function getMinisters()
    setImagePath(localPath .. "image")
    while (not (findImage(ministery, RegScreen))) do
        dragDrop(Point_2, Point_1)
    end
    num = sendToTrip
    if (getNotCollectedReg(ministery, RegScreen)) then
        wait(1)
        setImagePath(localPath .. "image" .. ministeryImagePath)
        existsClick(ok, RegMiddle, 0.5)
        collectIt()
    --    trip(num)
        x1 = 0
        x2 = 0
        y = 0
        for i = 2, 8 do

            mImg = Pattern("m" .. i .. ".png")
            if findImage(mImg, RegHalfBottom) then
                click(image_Center)
                wait(0.2)
                if (i == 4) then
                    x2 = image_Center:getX()
                    y = image_Center:getY()
                    p2 = Location(x2, y)
                    p1 = Location(10, y)
                    dragDrop(p2, p1)
                    dragDrop(p2, p1)

                end
                collectIt()
                if (i > 3) then
                    trip(num - i)
                else
                    trip(num)
                end
            else
                break ;
            end

        end
        setImagePath(localPath .. "image")
        wait(1)
        backTo(ministery)
    end
end

function collectIt()
    wait(0.2)
    if (findImageLowSimilar(box, RegScreen)) then
        click(Location(screenX / 2, screenY / 2 - screenY / 6))

        while (not (findImage(ok, RegQuaterBottom))) do
            wait(0.05)
        end
        okBtn, okCenter = findImage(ok, RegQuaterBottom)
        click(okCenter)
        y = okCenter:getY() - okCenter:getY() * 0.02
        while (not (findImage(chance, RegHalfBottom))) do
            wait(0.05)
            click(Location(okCenter:getX(), y))

        end
    end
end

function trip(heirsNum)
    if (isSendToTrip and heirsNum ~= 0) then
        if (existsClick(startTrip, RegHalfBottom, 0.1)) then
            while (not(findImage(scroll, RegMiddle))) do
                wait(0.1)
            end
            usePreviousSnap(true)
            existsClick(cbxSendAll, RegHalfBottom, 0.1)
            usePreviousSnap(false)
            existsClick(sendBtn, RegHalfBottom, 0.1)

            while (not(findImage(addMore, RegHalfBottom))) do
                wait(0.1)
            end
            usePreviousSnap(true)
            img, c = findImage(addMore, RegHalfBottom)
            for i = 1, heirsNum do
                click(c)
                wait(0.05)
            end
            existsClick(confirmSend, RegHalfBottom, 0.1)
            usePreviousSnap(false)
            wait(0.1)
            click(Location(screenX / 2, screenY / 2))
            wait(0.1)
            waitExistAndClick(scroll, RegMiddle, 0.1)
            waitExistAndClick(xx2, RegHalfUp, 0.1)
        end
    end
end