---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 08.01.2020 23:57
---
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")


function infPalaceCollect()
    setImagePath(localPath .. "image")
    if (not (findImage(autoCollect, RegHalfBottom))) then
        while (existsClick(collectRes, RegScreen, 0.1)) do
        end
    else
        click(image_Center)
    end
end


function collectPalaceGoods()

    setImagePath(localPath .. "image")
    while (not (findImage(dvorec, RegHalfUp))) do
        dragDrop(Point_1, Point_2)
    end
    xC = -1
    yC = -1
    if (existsClick(dvorec, RegHalfUp, 1)) then
        if (existsClick(sinan, RegScreen, 1)) then
            while (findImage(orders, RegQuaterBottom)) do
                if (ordersExperience) then
                    for i = 1, 5 do
                        click(image_Center)
                    end
                    existsClick(xx2, RegScreen, 0.2)
                else
                    if (xC == -1) then
                        xC = image_Center:getX()
                        yC = image_Center:getY()
                    end
                    for i = 1, 5 do
                        click(Location(xC, yC * 0.94))
                    end
                end
            end
        end
        backTo(melek)
        if (existsClick(melek, RegScreen,1)) then
            if (not (findImage(autoCollect, RegHalfBottom))) then
                while (existsClick(collectRes, RegScreen, 0.1)) do
                end
            else
                click(image_Center)
            end
            wait(1)
        end
        backTo(dvorec)
    end
end


