---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 28.05.2020 13:41
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "sultanObjects")

function guardRgmt()
    setImagePath(localPath .. "image" .. rgmtPath)
    for i = 1, 300 do
        waitExistAndClick(newFight, RegQuaterBottom, 0.1)
        waitExistAndClick(skipAnim, RegQuaterBottom, 0.1)
        waitExistAndClick(nextFight, RegHalfBottom, 0.1)
    end
    setImagePath(localPath .. "image")
end

function oneFight()
    waitExistAndClick(polk, RegScreen, 0.1)
    setImagePath(localPath .. "image" .. rgmtPath)
    waitExistAndClick(training, RegScreen, 0.1)
    waitExistAndClick(chooseFightingLvl, RegScreen, 0.1)
    waitExistAndClick(newFight, RegQuaterBottom, 0.1)
    waitExistAndClick(skipAnim, RegQuaterBottom, 0.1)
    click(pCenter)
    click(pCenter)
    setImagePath(localPath .. "image")
    backTo(polk)

end