---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DrBlast.
--- DateTime: 11.01.2020 22:27
---
localPath = scriptPath()
require(localPath .. "utils")
require(localPath .. "dialog")
require(localPath .. "sultanObjects")

function walking()
    while (not (findImage(renewWalk, RegQuaterBottom))) do
        click(Location(x, y))
        wait(0.1)
    end
end

function goForAWalk()
    setImagePath(localPath .. "image")
    while (not (findImage(exitToTown, RegScreen))) do
        dragDrop(Point_1, Point_2)
    end
    existsClick(exitToTown, RegScreen, 1)

    setImagePath(localPath .. "image" .. townPath)
    local x = screenX * 0.84
    local y = screenY * 0.948

    local isRenew = false
    if (findImage(energy, RegQuaterBottom) or findImage(energy2, RegQuaterBottom)) then
        isRenew = true
    end

    walking()
    if (isRenew and isPuzzle) then
        while (not (findImage(apply, RegMiddle))) do
            click(Location(x, y))
        end
        usePreviousSnap(true)
        waitExistAndClick(apply, RegMiddle, 0.2)
        usePreviousSnap(false)
        walking()
    end
    existsClick(xx2, RegScreen, 0.1)
    setImagePath(localPath .. "image")
    backTo(exitToTown)
end
